import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  SafeAreaView,
  StatusBar,
  TouchableOpacity,
  Modal,
  Dimensions,
  Platform,
} from 'react-native';
import { BG, COLORS, scaleFont, scaleSize, SCREEN, IS_DESKTOP, CONTENT_MAX_WIDTH } from '../theme';
import { Ionicons } from '@expo/vector-icons';
import AsyncStorage from '@react-native-async-storage/async-storage';

const SCREEN_W = SCREEN.width;

const getHistoryKey = (name) => `antriksh_typing_history_${name || 'default'}`;

export default function StatsScreen({ studentName, onBack }) {
  const [records, setRecords] = useState([]);
  const [showSpeedDetail, setShowSpeedDetail] = useState(false);
  const [showAccDetail, setShowAccDetail] = useState(false);
  const [reportVisible, setReportVisible] = useState(false);

  const today = new Date().toLocaleDateString();

  useEffect(() => {
    const key = getHistoryKey(studentName);
    AsyncStorage.getItem(key)
      .then((raw) => {
        try {
          const all = raw ? JSON.parse(raw) : [];
          const todays = all.filter((r) => r.date === today);
          setRecords(todays);
        } catch { setRecords([]); }
      })
      .catch(() => setRecords([]));
  }, []);

  const totalTests = records.length;
  const bestWpm = totalTests > 0 ? Math.max(...records.map((r) => r.wpm)) : 0;
  const bestAccuracy = totalTests > 0 ? Math.max(...records.map((r) => r.accuracy)) : 0;
  const totalPracticeSec = records.reduce((sum, r) => sum + (r.timeTaken || 0), 0);
  const practiceHours = Math.floor(totalPracticeSec / 3600);
  const practiceMin = Math.floor((totalPracticeSec % 3600) / 60);
  const practiceTime = totalPracticeSec > 0
    ? practiceHours > 0 ? `${practiceHours}h ${practiceMin}m` : `${practiceMin}m`
    : '0m';

  const getDifficultKeys = () => {
    const keyMap = {};
    records.forEach((r) => {
      if (r.mistakes > 0) {
        const lesson = r.lesson || 'Unknown';
        if (!keyMap[lesson]) keyMap[lesson] = 0;
        keyMap[lesson] += r.mistakes;
      }
    });
    return Object.entries(keyMap).sort((a, b) => b[1] - a[1]).slice(0, 5).map(([lesson, count]) => ({ lesson, count }));
  };

  const difficultKeys = getDifficultKeys();

  const generateReport = () => {
    const date = new Date().toLocaleDateString();
    const time = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
    const avgWpm = totalTests > 0 ? Math.round(records.reduce((s, r) => s + r.wpm, 0) / totalTests) : 0;
    const avgAcc = totalTests > 0 ? Math.round(records.reduce((s, r) => s + r.accuracy, 0) / totalTests) : 0;
    const totalErr = records.reduce((sum, r) => sum + (r.mistakes || 0), 0);
    let report = `========================================\n`;
    report += `       TYPING PROGRESS REPORT\n`;
    report += `========================================\n\n`;
    report += `Student: ${studentName}\n`;
    report += `Date: ${date}\n`;
    report += `Time: ${time}\n\n`;
    report += `----------------------------------------\n`;
    report += `           TODAY'S STATISTICS\n`;
    report += `----------------------------------------\n`;
    report += `Total Tests:     ${totalTests}\n`;
    report += `Practice Time:   ${practiceTime}\n`;
    report += `Best Speed:      ${bestWpm} WPM\n`;
    report += `Average Speed:   ${avgWpm} WPM\n`;
    report += `Best Accuracy:   ${bestAccuracy}%\n`;
    report += `Average Accuracy:${avgAcc}%\n`;
    report += `Total Errors:    ${totalErr}\n\n`;
    report += `----------------------------------------\n`;
    report += `           RECENT TESTS\n`;
    report += `----------------------------------------\n`;
    records.slice(0, 10).forEach((r, i) => {
      report += `${i + 1}. ${r.lesson} | ${r.wpm} WPM | ${r.accuracy}% | ${r.time}\n`;
    });
    if (difficultKeys.length > 0) {
      report += `\n----------------------------------------\n`;
      report += `           DIFFICULT AREAS\n`;
      report += `----------------------------------------\n`;
      difficultKeys.forEach((d) => { report += `${d.lesson}: ${d.count} errors\n`; });
    }
    report += `\n========================================\n`;
    report += `       Generated by Typing Master\n`;
    report += `========================================\n`;
    return report;
  };

  const handlePrint = () => {
    const report = generateReport();
    if (Platform.OS === 'web') {
      const printWindow = window.open('', '_blank');
      if (printWindow) {
        printWindow.document.write(`<pre style="font-family:monospace;font-size:14px;">${report}</pre>`);
        printWindow.document.close();
        printWindow.print();
      }
    }
  };

  const handleSave = () => {
    const report = generateReport();
    if (Platform.OS === 'web') {
      const blob = new Blob([report], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `typing-report-${new Date().toISOString().slice(0, 10)}.txt`;
      a.click();
      URL.revokeObjectURL(url);
    }
  };

  return (
    <SafeAreaView style={styles.safeArea}>
      <StatusBar barStyle="light-content" />
      <View style={styles.gradient}>
          <ScrollView contentContainerStyle={[styles.container, IS_DESKTOP && styles.containerDesktop]}>
          {/* Header */}
          <View style={styles.header}>
            {onBack && (
              <TouchableOpacity onPress={onBack} style={styles.backBtn} activeOpacity={0.7}>
                <Ionicons name="arrow-back" size={20} color={COLORS.textWhite} />
              </TouchableOpacity>
            )}
            <Ionicons name="stats-chart" size={22} color={COLORS.teal} />
            <Text style={styles.headerTitle}>Statistics</Text>
          </View>

          {/* Stats overview */}
          <View style={styles.overviewRow}>
            <View style={[styles.overviewCard, { borderLeftColor: COLORS.teal }]}>
              <Ionicons name="speedometer" size={20} color={COLORS.teal} />
              <Text style={[styles.overviewVal, { color: COLORS.teal }]}>{bestWpm}</Text>
              <Text style={styles.overviewLabel}>Best WPM</Text>
            </View>
            <View style={[styles.overviewCard, { borderLeftColor: COLORS.green }]}>
              <Ionicons name="checkmark-circle" size={20} color={COLORS.green} />
              <Text style={[styles.overviewVal, { color: COLORS.green }]}>{bestAccuracy}%</Text>
              <Text style={styles.overviewLabel}>Accuracy</Text>
            </View>
            <View style={[styles.overviewCard, { borderLeftColor: COLORS.amber }]}>
              <Ionicons name="time" size={20} color={COLORS.amber} />
              <Text style={[styles.overviewVal, { color: COLORS.amber }]}>{practiceTime}</Text>
              <Text style={styles.overviewLabel}>Practice</Text>
            </View>
          </View>

          {/* Main Card */}
          <View style={styles.card}>
            <View style={styles.tabRow}>
              <TouchableOpacity
                style={[styles.tab, showSpeedDetail && { backgroundColor: COLORS.teal + '20', borderColor: COLORS.teal + '50' }]}
                onPress={() => { setShowSpeedDetail(!showSpeedDetail); setShowAccDetail(false); }}
                activeOpacity={0.7}
              >
                <Ionicons name="speedometer" size={16} color={showSpeedDetail ? COLORS.teal : COLORS.textMuted} />
                <Text style={[styles.tabText, showSpeedDetail && { color: COLORS.teal, fontFamily: 'Calibri', fontWeight: '700'}]}>Speed</Text>
              </TouchableOpacity>
              <TouchableOpacity
                style={[styles.tab, showAccDetail && { backgroundColor: COLORS.green + '20', borderColor: COLORS.green + '50' }]}
                onPress={() => { setShowAccDetail(!showAccDetail); setShowSpeedDetail(false); }}
                activeOpacity={0.7}
              >
                <Ionicons name="checkmark-circle" size={16} color={showAccDetail ? COLORS.green : COLORS.textMuted} />
                <Text style={[styles.tabText, showAccDetail && { color: COLORS.green, fontFamily: 'Calibri', fontWeight: '700'}]}>Accuracy</Text>
              </TouchableOpacity>
            </View>

            {showSpeedDetail && (
              <View style={styles.detailBox}>
                <View style={styles.contentRow}>
                  <Text style={styles.contentLabel}>Best Speed</Text>
                  <Text style={[styles.contentValue, { color: COLORS.teal }]}>{bestWpm} WPM</Text>
                </View>
                <View style={styles.contentRow}>
                  <Text style={styles.contentLabel}>Average Speed</Text>
                  <Text style={[styles.contentValue, { color: COLORS.teal }]}>
                    {totalTests > 0 ? Math.round(records.reduce((s, r) => s + r.wpm, 0) / totalTests) : 0} WPM
                  </Text>
                </View>
              </View>
            )}

            {showAccDetail && (
              <View style={styles.detailBox}>
                <View style={styles.contentRow}>
                  <Text style={styles.contentLabel}>Best Accuracy</Text>
                  <Text style={[styles.contentValue, { color: COLORS.green }]}>{bestAccuracy}%</Text>
                </View>
                <View style={styles.contentRow}>
                  <Text style={styles.contentLabel}>Average Accuracy</Text>
                  <Text style={[styles.contentValue, { color: COLORS.green }]}>
                    {totalTests > 0 ? Math.round(records.reduce((s, r) => s + r.accuracy, 0) / totalTests) : 0}%
                  </Text>
                </View>
              </View>
            )}

            <TouchableOpacity style={styles.reportBtn} onPress={() => setReportVisible(true)} activeOpacity={0.7}>
              <Ionicons name="document-text" size={16} color={COLORS.teal} />
              <Text style={styles.reportBtnText}>View Progress Report</Text>
            </TouchableOpacity>
          </View>
        </ScrollView>

        {/* Report Modal */}
        <Modal visible={reportVisible} transparent animationType="fade">
          <View style={styles.modalOverlay}>
            <View style={styles.modalCard}>
              <View style={styles.modalHeader}>
                <Text style={styles.modalTitle}>Progress Report</Text>
                <TouchableOpacity onPress={() => setReportVisible(false)}>
                  <Ionicons name="close" size={22} color={COLORS.textWhite} />
                </TouchableOpacity>
              </View>
              <ScrollView style={styles.modalBody}>
                <Text style={styles.reportText}>{generateReport()}</Text>
              </ScrollView>
              <View style={styles.modalActions}>
                <TouchableOpacity style={[styles.modalBtn, { backgroundColor: COLORS.green }]} onPress={handleSave} activeOpacity={0.7}>
                  <Ionicons name="download" size={14} color="#fff" />
                  <Text style={styles.modalBtnText}>Save</Text>
                </TouchableOpacity>
                <TouchableOpacity style={[styles.modalBtn, { backgroundColor: COLORS.teal }]} onPress={handlePrint} activeOpacity={0.7}>
                  <Ionicons name="print" size={14} color="#fff" />
                  <Text style={styles.modalBtnText}>Print</Text>
                </TouchableOpacity>
                <TouchableOpacity style={[styles.modalBtn, { backgroundColor: COLORS.green }]} onPress={() => setReportVisible(false)} activeOpacity={0.7}>
                  <Ionicons name="close" size={14} color="#fff" />
                  <Text style={styles.modalBtnText}>Close</Text>
                </TouchableOpacity>
              </View>
            </View>
          </View>
        </Modal>
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: BG },
  gradient: { flex: 1 },
  container: { flexGrow: 1, padding: scaleFont(16), paddingBottom: 40 },
  containerDesktop: {
    padding: 24,
    paddingBottom: 24,
    maxWidth: CONTENT_MAX_WIDTH,
    alignSelf: 'center',
    width: '100%',
  },

  header: { flexDirection: 'row', alignItems: 'center', gap: scaleSize(8), marginBottom: scaleFont(14) },
  backBtn: {
    width: scaleSize(38), height: scaleSize(38), borderRadius: scaleSize(19),
    alignItems: 'center', justifyContent: 'center',
    backgroundColor: COLORS.cardBg, borderWidth: 1, borderColor: COLORS.cardBorder,
  },
  headerTitle: { fontSize: scaleFont(22), fontFamily: 'Calibri', fontWeight: '700', color: COLORS.textWhite, flex: 1 },

  overviewRow: { flexDirection: 'row', gap: scaleSize(8), marginBottom: scaleFont(14) },
  overviewCard: {
    flex: 1, backgroundColor: COLORS.cardBg, borderRadius: scaleSize(12),
    borderWidth: 1, borderColor: COLORS.cardBorder, padding: scaleSize(10),
    alignItems: 'center', borderLeftWidth: 3,
  },
  overviewVal: { fontSize: scaleFont(20), fontFamily: 'Calibri', fontWeight: '700', marginTop: scaleSize(4) },
  overviewLabel: { fontSize: scaleFont(10), color: COLORS.textMuted, fontFamily: 'Calibri', fontWeight: '700', marginTop: scaleSize(2) },

  card: {
    backgroundColor: COLORS.cardBgSolid,     borderRadius: scaleSize(18),
    borderWidth: 1, borderColor: COLORS.cardBorder, padding: scaleSize(16),
  },
  tabRow: { flexDirection: 'row', gap: scaleSize(10), marginBottom: scaleFont(14) },
  tab: {
    flex: 1, paddingVertical: scaleFont(12), paddingHorizontal: scaleFont(14),
    borderRadius: scaleSize(12), borderWidth: 1, borderColor: COLORS.cardBorder,
    backgroundColor: 'rgba(255,255,255,0.06)', alignItems: 'center',
    flexDirection: 'row', justifyContent: 'center', gap: scaleSize(6),
  },
  tabText: { fontSize: scaleFont(14), color: COLORS.textMuted, fontFamily: 'Calibri', fontWeight: '700'},

  detailBox: {
    backgroundColor: 'rgba(255,255,255,0.06)', borderRadius: scaleSize(14),
    borderWidth: 1, borderColor: COLORS.cardBorder, padding: scaleSize(14),
    marginBottom: scaleSize(12),
  },
  contentRow: { paddingVertical: scaleFont(10), borderBottomWidth: 1, borderBottomColor: COLORS.cardBorder },
  contentLabel: { fontSize: scaleFont(13), fontFamily: 'Calibri', fontWeight: '700', color: COLORS.textLight },
  contentValue: { fontSize: scaleFont(22), fontFamily: 'Calibri', fontWeight: '700', marginTop: scaleSize(4) },

  reportBtn: {
    flexDirection: 'row', alignItems: 'center', gap: scaleSize(8), paddingTop: scaleSize(12),
  },
  reportBtnText: { fontSize: scaleFont(15), color: COLORS.teal, fontFamily: 'Calibri', fontWeight: '700'},

  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', justifyContent: 'center', padding: scaleSize(20) },
  modalCard: { backgroundColor: '#1a1a2e', borderRadius: scaleSize(18), borderWidth: 1, borderColor: COLORS.cardBorder, maxHeight: '80%' },
  modalHeader: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    padding: scaleSize(16), borderBottomWidth: 1, borderBottomColor: COLORS.cardBorder,
  },
  modalTitle: { fontSize: scaleFont(18), color: COLORS.textWhite, fontFamily: 'Calibri', fontWeight: '700'},
  modalBody: { padding: scaleSize(16), maxHeight: 350 },
  reportText: { fontFamily: 'Calibri', color: COLORS.textLight, fontSize: scaleFont(12), lineHeight: scaleSize(20) },
  modalActions: {
    flexDirection: 'row', justifyContent: 'space-between',
    padding: scaleSize(16), borderTopWidth: 1, borderTopColor: COLORS.cardBorder, gap: scaleSize(8),
  },
  modalBtn: {
    flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    gap: scaleSize(4), borderRadius: scaleSize(10), paddingVertical: scaleSize(10),
  },
  modalBtnText: { color: '#fff', fontSize: scaleFont(12), fontFamily: 'Calibri', fontWeight: '700'},
});
